blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android
    about: Submit your ideas to improve Thunderbird for Android
  - name: Mozilla support forum (SUMO)
    url: https://support.mozilla.org/products/thunderbird-android
    about: Many issues are not bugs, ask the community for help
