appId: net.thunderbird.android.debug
---
- runFlow:
    file: ../shared/onboard_with_demo_account.yml
    when:
      visible:
        id: "onboarding_welcome_start_button"

## Start composing
- tapOn:
    id: "net.thunderbird.android.debug:id/floating_action_button"

## Compose email

## To
- tapOn:
    id: "net.thunderbird.android.debug:id/to"
- inputText: "simple_compose@example.com"

## Subject
- tapOn:
    id: "net.thunderbird.android.debug:id/subject"
- inputText: "Simple compose test"

## Message
- tapOn:
    id: "net.thunderbird.android.debug:id/message_content"
- inputText: "Lorem ipsum dolor sit amet."

## Send
- tapOn:
    id: "net.thunderbird.android.debug:id/send"

## Open message
- tapOn:
    id: "net.thunderbird.android.debug:id/subject"
    index: 0
    text: "Simple compose test"

## Assert
- assertVisible:
    id: "net.thunderbird.android.debug:id/subject"
    text: "Simple compose test"
- assertVisible:
    id: "net.thunderbird.android.debug:id/from"
    text: "Demo User"
- assertVisible:
    id: "net.thunderbird.android.debug:id/recipient_names"
    text: "to simple_compose@example.com"

## Delete message
- tapOn:
    id: "net.thunderbird.android.debug:id/delete"
- assertNotVisible:
    id: "net.thunderbird.android.debug:id/subject"
    text: "Simple compose test"
