#2023-09-23 10:30
name: act - Android CI

on:
#  pull_request:
#    paths-ignore:
#      - '.idea/**'
#      - '.gitattributes'
#      - '.github/**.json'
#      - '.gitignore'
#      - '.gitmodules'
#      - '**.md'
#      - 'LICENSE'
#      - 'NOTICE'
  workflow_dispatch:

env:
  PRG_NAME: "k9mail"
  PRG_VERSION: "v6.704"
  TAG_NAME: "k9mail"
  TAG_VERSION: "v6.704"
  TAG_BUILD: "-b"
  TAG_REF: "0000000"
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  #  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #  alias: ${{ secrets.ANDROID_ALIAS }}
  #  keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
  #  keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}  

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: deep-soft/checkout@v3

      - name: Get ref, set build version
        shell: bash
        run: |
          _ref_all_=$(git log -1 --format='%H')
          # _ref_=$(echo ${_ref_all_::7})
          _ref_org_=${{ env.TAG_REF }}
          _ref_len_="${#_ref_org_}"
          _ref_=$(echo ${_ref_all_::$_ref_len_})
          _prg_version_=$(grep versionName "app/k9mail/build.gradle.kts" | awk -F '= ' '{print $2}' | awk -F '"' '{print $2}')
          echo "TAG_REF=$_ref_" >> $GITHUB_ENV
          _build_=${{ env.TAG_BUILD }}.$_ref_
          echo "TAG_BUILD=$_build_" >> $GITHUB_ENV
          echo "PRG_VERSION=$_prg_version_" >> $GITHUB_ENV
          echo "TAG_VERSION=$_prg_version_" >> $GITHUB_ENV

      - name: Print ref, build version
        shell: bash
        run: |
          echo "VER: ${{ env.PRG_VERSION }}
          echo "TAG: ${{ env.TAG_VERSION }}
          echo "REF: ${{ env.TAG_REF }}
          echo "BLD: ${{ env.TAG_BUILD }}
          echo "${{ env.TAG_NAME }}-${{ env.TAG_BUILD }}" > _tag_name_.txt

      - name: Create source archive
        continue-on-error: true
        shell: bash
        run: |
          staging="${{ env.PRG_NAME }}-src-${{ env.PRG_VERSION }}-${{ env.TAG_BUILD }}"
          touch "$staging.tar.xz"
          tar --exclude=*.tar* -cv . | xz -9 > "$staging.tar.xz"
          echo "ASSET_SRC=$staging.tar.xz" >> $GITHUB_ENV
          if [ "${{ env.DEBUG_LS }}" = "yes" ]; then
            echo "source archive name: "
            ls -l "$staging.tar.xz"
          fi

      - name: Publish src archive
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{ env.ASSET_SRC }}

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      # - run: ./gradlew assembleDebug detekt spotlessCheck testsOnCi
      - run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: deep-soft/upload-artifact@v3
        with:
          name: upload-artifact
          path: |
            ./app/${{ env.PRG_NAME }}/build/outputs/apk/

      - name: Copy apk from outputs/
        shell: bash
        run: |
          set -x
          mkdir -p signed-apk
          echo "LIST: " ./app/${{ env.PRG_NAME }}/build/outputs/apk/release/
          ls -l ./app/${{ env.PRG_NAME }}/build/outputs/apk/release/
          cp ./app/${{ env.PRG_NAME }}/build/outputs/apk/release/* ./signed-apk/
          echo "LIST: " ./signed-apk/
          ls -l ./signed-apk/
          mv ./signed-apk/k9mail-release-unsigned.apk ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk
          echo "LIST: " ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk
          ls -l ./signed-apk/

      - uses: deep-soft/sign-android-release@master
        name: Sign app APK
        if: env.ANDROID_SIGNING_KEY != null
        id: sign-k9mail
        with:
          releaseDirectory: ./signed-apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload Artifacts
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/upload-artifact@v3
        with:
          name: ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.apk
          path: ${{steps.sign-k9mail.outputs.signedReleaseFile}}

      - name: Publish signed apk package
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ${{steps.sign-k9mail.outputs.signedReleaseFile}}
            _tag_name_.txt

      - name: Publish version build - signed apk package
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{steps.sign-k9mail.outputs.signedReleaseFile}}
            _tag_name_.txt

      - name: Publish unsigned apk package
        if: env.ANDROID_SIGNING_KEY == null
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-unsigned.apk
            _tag_name_.txt
